import React from 'react'
import cash from '../../assets/imgs/cash.png'

function Revenue() {
    return (
        <>
            <section className="overflow-hidden">
                <h1 class="fontAlt sm:text-6xl mb-4 font-bold text-start text-gray-900"><span className='text-primColor1'>REVENUE GENERATED</span></h1>
                <div class="flex items-center justify-between bg-white px-8 text-white shadow-sm rounded-lg border-1">
                    <div class="my-10 lg:my-8 lg:w-1/2">
                        <h1 class="text-8xl font-bold fontAlt tracking-wide text-primColor1">$4800</h1>
                        <p class="mt-2 text-lg text-gray-700">The total revenue generated by the proeffiecy of 2% from both vendors and shippers.</p>
                    </div>
                    <div class="hidden h-22 w-1/2 flex-shrink-0 justify-end lg:flex">
                        <img class="w-52" src={cash} alt="pic" />
                    </div>
                </div>

                <div class="w-full overflow-x-auto fontAlt rounded-lg shadow-sm border-1 border-gray-250 mt-4">

                    <div class="bg-white py-4 md:py-7 px-4 md:px-8 xl:px-10">
                        <div class="sm:flex items-center justify-between">
                            <div class="relative mb-1">
                                <label for="email" class="leading-7 text-sm text-gray-600">Sort by date</label>
                                <input type="date" class="w-full bg-white rounded-sm border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" />
                            </div>
                            <button class="focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600 sm:mt-0 inline-flex items-center justify-center px-6 py-2 bg-green-400 text-white hover:bg-indigo-600 focus:outline-none rounded">
                                Sort
                            </button>
                        </div>

                        <div class="mt-7 overflow-x-auto">
                            <table class="w-full text-left border-1 border-gray-300 relative overflow-x-auto shadow-md sm:rounded-lg">
                                <tbody class='bg-white rounded-lg'>
                                    <tr class='rounded-lg text-sm text-gray-700 uppercase'>
                                        <th scope="col" class="h-10 px-4 border-l py-3 font-medium first:border-l-0 stroke-slate-700 text-slate-700 bg-slate-200">Date</th>
                                        <th scope="col" class="h-10 px-4 text-m font-medium border-l first:border-l-0 stroke-slate-700 text-slate-700 bg-slate-200">Revenue Generated</th>
                                        {/* <th scope="col" class="h-10 px-4 text-m font-medium border-l first:border-l-0 stroke-slate-700 text-slate-700 bg-slate-200">Email</th> */}
                                        {/* <th scope="col" class="h-10 px-4 text-m font-medium border-l first:border-l-0 stroke-slate-700 text-slate-700 bg-slate-200"></th> */}
                                    </tr>

                                    <tr class='rounded-lg'>
                                        <td class="h-10 px-4 text-sm transition duration-300 border-t border-l py-3 first:border-l-0 border-slate-200 stroke-slate-500 text-slate-500">02/08/2024</td>
                                        <td class="h-10 px-4 text-sm transition duration-300 border-t border-l first:border-l-0 border-slate-200 stroke-slate-500 text-slate-500">$ 450</td>
                                        {/* <td class="h-10 px-4 text-sm transition duration-300 border-t border-l first:border-l-0 border-slate-200 stroke-slate-500 text-slate-500">atharaza.dev@gmail.com</td> */}
                                        {/* <td class="h-10 px-4 text-sm transition duration-300 border-t border-l first:border-l-0 border-slate-200 stroke-slate-500 text-slate-500 justify-center items-center last-cell-width">
                                            <center>
                                                <button class="text-white bg-blue-700 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded inline-block">Edit Shipper Details</button>
                                            </center>
                                        </td> */}
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

            </section >
        </>
    )
}

export default Revenue
